# Generated by Django 3.0.2 on 2020-04-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mob', models.CharField(max_length=100)),
                ('fever', models.IntegerField()),
                ('tired', models.BooleanField(default=False)),
                ('throat', models.BooleanField(default=False)),
                ('bodypain', models.BooleanField(default=False)),
                ('invisit', models.BooleanField(default=False)),
                ('pubvisit', models.BooleanField(default=False)),
                ('hivisit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
