# Generated by Django 3.0.2 on 2020-04-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Covidiot',
        ),
    ]
