# Generated by Django 3.0.2 on 2020-04-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidManager', '0002_auto_20200413_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidiot',
            name='ctscan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='covidiot',
            name='xray',
            field=models.BooleanField(default=False),
        ),
    ]
