# Generated by Django 3.0.2 on 2020-04-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidManager', '0003_auto_20200414_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidiot',
            name='friends',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='covidiot',
            name='pending_in',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='covidiot',
            name='pending_out',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
    ]
