# Generated by Django 3.0.2 on 2020-04-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidManager', '0005_auto_20200416_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='covidiot',
            name='iv',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
